package shitcompiler.parser

import shitcompiler.token.Symbol.*

/**
 * Created by NuclearCoder on 26/01/17.
 */

val ADD_SYMBOLS = setOf(PLUS, MINUS, AND, OR)

val MULTIPLY_SYMBOLS = setOf(ASTERISK, DIV, MOD, GREATER, NOT_GREATER, LESSER, NOT_LESSER, EQUAL, NOT_EQUAL)

val DECLARATION_SYMBOLS = setOf(INT, BOOL, CHAR, STRUCT)

val STATEMENT_SYMBOLS = setOf(BEGIN, ID, SEMICOLON) + DECLARATION_SYMBOLS

val UNARY_SYMBOLS = setOf(PLUS, MINUS, NOT)

val ASSIGNMENT_SYMBOLS = setOf(BECOMES, BECOMES_PLUS, BECOMES_MINUS, BECOMES_TIMES, BECOMES_DIV, BECOMES_MOD)

val SELECTOR_SYMBOLS = setOf(LEFT_BRACKET, PERIOD)