package shitcompiler.token

/**
* Created by NuclearCoder on 14/01/2017.
*/

enum class Symbol {
    ID, NUM_CONST, CHAR_CONST,
    RECORD, SEMICOLON, BEGIN, END,
    STATIC, INT, BOOL, CHAR,
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
    LEFT_BRACKET, RIGHT_BRACKET,
    IF, ELSE, WHILE, RETURN, BREAK,
    BECOMES,
    BECOMES_PLUS, BECOMES_MINUS, BECOMES_TIMES, BECOMES_DIV,
    DOUBLE_PLUS, DOUBLE_MINUS,
    OR, AND, NOT,
    LESSER, GREATER, NOT_LESSER, NOT_GREATER, EQUAL, NOT_EQUAL,
    PLUS, MINUS, ASTERISK, DIV, MOD, QUESTION_MARK,
    PERIOD, COMMA,
    TRUE, FALSE,
    NEWLINE, UNKNOWN

}